// journey-evidence.jsx — Forensic PDF evidence bundle + DMCA takedown notice

// ───── Forensic PDF Evidence Bundle (multi-page artboard) ─────
function PDF_Page({ children, n, of }) {
  return (
    <div style={{
      width: 612, // US Letter @ 72dpi width-ish (we'll scale)
      minHeight: 792,
      background: '#FBF8EE',
      boxShadow: '0 18px 40px -20px rgba(64,38,22,.30), 0 1px 0 rgba(64,38,22,.08)',
      padding: '52px 56px 48px',
      fontFamily: J_FONT, color: J_C.fg1,
      position: 'relative', overflow: 'hidden',
      borderRadius: 2,
    }}>
      <GridBg size={20} alpha={.025} />
      {/* Page chrome */}
      <div style={{ position: 'relative', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: `1px solid ${J_C.line2}`, paddingBottom: 14 }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none">
            <path d="M12 2 3 5v6c0 5 3.8 9.5 9 11 5.2-1.5 9-6 9-11V5l-9-3Z" stroke={J_C.primary} strokeWidth="1.6"/>
            <path d="M12 7v10M7 12h10" stroke={J_C.primary} strokeWidth="1.6"/>
          </svg>
          <Mono size={10} weight={700} color={J_C.fg1} style={{ letterSpacing: '.22em' }}>BOOK<span style={{ color: J_C.primary }}>SENTINEL</span> · FORENSIC EVIDENCE</Mono>
        </div>
        <Mono size={9} color={J_C.fg3} style={{ letterSpacing: '.22em' }}>NOTICE-2031 · PAGE {n}/{of}</Mono>
      </div>
      <div style={{ position: 'relative', paddingTop: 22 }}>{children}</div>
      <div style={{ position: 'absolute', left: 56, right: 56, bottom: 28, display: 'flex', justifyContent: 'space-between' }}>
        <Mono size={9} color={J_C.fg3} style={{ letterSpacing: '.22em' }}>CONFIDENTIAL · CASE T-2031</Mono>
        <Mono size={9} color={J_C.fg3} style={{ letterSpacing: '.22em' }}>SHA-256: 7E92…A4FB · SIGNED 2026-05-14T14:11:08Z</Mono>
      </div>
    </div>
  );
}

const PdfH1 = ({ children, mt = 0 }) => (
  <div style={{ marginTop: mt, fontFamily: J_FONT, fontSize: 28, fontWeight: 800, letterSpacing: '-0.025em', color: J_C.fg1, lineHeight: 1.1 }}>{children}</div>
);
const PdfH2 = ({ children, mt = 24 }) => (
  <div style={{ marginTop: mt, fontFamily: J_MONO, fontSize: 10, fontWeight: 700, letterSpacing: '.28em', color: J_C.primary, textTransform: 'uppercase', borderBottom: `1px solid ${J_C.line}`, paddingBottom: 6, marginBottom: 12 }}>{children}</div>
);
const PdfP = ({ children, mt = 8 }) => (
  <div style={{ marginTop: mt, fontFamily: J_FONT, fontSize: 11.5, lineHeight: 1.55, color: J_C.fg1, maxWidth: 520 }}>{children}</div>
);
const PdfKV = ({ k, v, mono = false }) => (
  <div style={{ display: 'flex', justifyContent: 'space-between', padding: '6px 0', borderBottom: `1px solid ${J_C.line}` }}>
    <Mono size={10} color={J_C.fg3} style={{ letterSpacing: '.18em' }}>{k}</Mono>
    {mono
      ? <Mono size={10.5} weight={500} color={J_C.fg1}>{v}</Mono>
      : <span style={{ fontFamily: J_FONT, fontSize: 11.5, color: J_C.fg1 }}>{v}</span>
    }
  </div>
);

function PDF_Bundle() {
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 24, padding: 24, background: J_C.bg1 }}>
      {/* COVER */}
      <PDF_Page n={1} of={4}>
        <Mono size={10} color={J_C.fg3} style={{ letterSpacing: '.28em' }}>EVIDENCE BUNDLE · COURT-ADMISSIBLE</Mono>
        <PdfH1 mt={8}>Forensic Capture<br/>NOTICE-2031</PdfH1>
        <PdfP mt={14}>
          Generated by BookSentinel v4.12 in response to a high-confidence detection of infringing material targeting protected intellectual property held by <b>Vanguard Press Ltd.</b> and signed by the authorized rights operator on the date and time recorded below.
        </PdfP>

        <div style={{ marginTop: 28, padding: 16, background: '#fff', border: `1px solid ${J_C.line2}`, borderRadius: 4, position: 'relative' }}>
          <FourCorners color={J_C.primary} />
          <PdfKV k="CASE ID" v="T-2031" mono />
          <PdfKV k="DETECTED AT" v="2026-05-14T12:14:33Z" mono />
          <PdfKV k="OPERATOR" v="O. KESTREL (Clearance A4)" mono />
          <PdfKV k="AUTHORIZED AT" v="2026-05-14T14:11:08Z" mono />
          <PdfKV k="BIOMETRIC SIGNATURE" v="FaceID · KS-0918-44F7" mono />
          <PdfKV k="RIGHTSHOLDER" v="Vanguard Press Ltd." />
          <PdfKV k="TITLE" v="Atlas of Fog (E. Marwick, 2024)" />
          <PdfKV k="ISBN" v="978-1-9988421-7-3" mono />
        </div>

        <div style={{ marginTop: 22, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 14 }}>
          <div style={{ padding: 12, border: `1px solid ${J_C.line2}`, borderRadius: 4, background: 'rgba(164,54,31,.06)' }}>
            <Mono size={9} color={J_C.fg3} style={{ letterSpacing: '.22em' }}>RISK</Mono>
            <div style={{ marginTop: 4, fontSize: 32, fontWeight: 800, color: J_C.destructive, letterSpacing: '-0.02em' }}>96<span style={{ fontSize: 14, color: J_C.fg3, marginLeft: 2 }}>/100</span></div>
          </div>
          <div style={{ padding: 12, border: `1px solid ${J_C.line2}`, borderRadius: 4 }}>
            <Mono size={9} color={J_C.fg3} style={{ letterSpacing: '.22em' }}>CONTENT MATCH</Mono>
            <div style={{ marginTop: 4, fontSize: 32, fontWeight: 800, color: J_C.success, letterSpacing: '-0.02em' }}>98.7%</div>
          </div>
        </div>

        <PdfH2>Executive Summary</PdfH2>
        <PdfP mt={0}>
          On 14 May 2026 at 12:14:33Z, BookSentinel Scout Agent <Mono color={J_C.fg1} size={11}>NEPTUNE</Mono> indexed an unauthorized digital reproduction of the work <i>Atlas of Fog</i> at <Mono color={J_C.fg1} size={11}>freebooks-vault[.]ru/atlas-of-fog</Mono>. The captured artefact is a 412-page PDF whose content fingerprint matches the rightsholder's master file at 98.7%, and whose embedded metadata retains the original publisher ISBN and cover artwork.
        </PdfP>
        <PdfP>
          The hosting domain is registered through <Mono color={J_C.fg1} size={11}>r01-registrar</Mono> and resolves to OVHcloud infrastructure in the Russian Federation (ASN 16276). 14 mirror endpoints have been catalogued; all are tracked in the BookSentinel Vector Registry under case lineage <Mono color={J_C.fg1} size={11}>T-2031</Mono>.
        </PdfP>
      </PDF_Page>

      {/* EVIDENCE PAGE */}
      <PDF_Page n={2} of={4}>
        <PdfH2 mt={0}>Visual Capture · Four Angles</PdfH2>
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 10 }}>
          {[
            { label: 'A · Index page',     line: 'GET /atlas-of-fog' },
            { label: 'B · Reader view',    line: 'GET /atlas-of-fog/reader' },
            { label: 'C · Download link',  line: 'GET /atlas-of-fog/download' },
            { label: 'D · Mirror map',     line: 'GET /atlas-of-fog/mirrors' },
          ].map(s => (
            <div key={s.label} style={{ border: `1px solid ${J_C.line2}`, borderRadius: 3, background: '#fff', padding: 8 }}>
              {/* synthetic screenshot */}
              <div style={{ height: 132, background: '#1a1207', borderRadius: 2, position: 'relative', overflow: 'hidden', padding: 8 }}>
                <div style={{ display: 'flex', gap: 4, marginBottom: 8 }}>
                  <div style={{ width: 6, height: 6, background: '#E27D5E', borderRadius: 99 }} />
                  <div style={{ width: 6, height: 6, background: '#E8B66A', borderRadius: 99 }} />
                  <div style={{ width: 6, height: 6, background: '#9CB37A', borderRadius: 99 }} />
                </div>
                <div style={{ fontFamily: J_MONO, fontSize: 7, color: 'rgba(255,248,236,.7)' }}>freebooks-vault.ru/atlas-of-fog</div>
                <div style={{ marginTop: 8, height: 4, background: 'rgba(255,248,236,.20)', width: '70%' }} />
                <div style={{ marginTop: 4, height: 2, background: 'rgba(255,248,236,.15)' }} />
                <div style={{ marginTop: 2, height: 2, background: 'rgba(255,248,236,.15)', width: '90%' }} />
                <div style={{ marginTop: 2, height: 2, background: 'rgba(255,248,236,.15)', width: '60%' }} />
                <div style={{ marginTop: 10, display: 'flex', gap: 4 }}>
                  <div style={{ width: 30, height: 38, background: 'linear-gradient(140deg, #6B5238, #2A1810)', borderRadius: 1 }} />
                  <div style={{ flex: 1 }}>
                    <div style={{ height: 3, background: 'rgba(255,248,236,.30)', marginBottom: 2 }} />
                    <div style={{ height: 2, background: 'rgba(255,248,236,.15)', marginBottom: 2 }} />
                    <div style={{ height: 2, background: 'rgba(255,248,236,.15)', marginBottom: 2 }} />
                    <div style={{ marginTop: 6, padding: '2px 6px', background: J_C.primary, color: '#FFF8EC', fontFamily: J_MONO, fontSize: 6, letterSpacing: '.18em', display: 'inline-block' }}>DOWNLOAD PDF</div>
                  </div>
                </div>
              </div>
              <div style={{ marginTop: 8, display: 'flex', justifyContent: 'space-between' }}>
                <Mono size={9} color={J_C.fg1} weight={700} style={{ letterSpacing: '.18em' }}>{s.label}</Mono>
                <Mono size={9} color={J_C.fg3}>{s.line}</Mono>
              </div>
            </div>
          ))}
        </div>

        <PdfH2>Vector Trace</PdfH2>
        <div style={{ padding: 14, background: '#fff', border: `1px solid ${J_C.line2}`, borderRadius: 3 }}>
          <PdfKV k="TARGET URL" v="freebooks-vault[.]ru/atlas-of-fog" mono />
          <PdfKV k="IP ADDRESS" v="51.222.84.119" mono />
          <PdfKV k="HOSTING ASN" v="AS16276 · OVH SAS" mono />
          <PdfKV k="REGISTRAR" v="r01-registrar.ru (IANA 1606)" mono />
          <PdfKV k="REGISTRANT" v="WHOIS-PROTECT (privacy proxy)" mono />
          <PdfKV k="CREATED" v="2026-05-13T22:48:00Z" mono />
          <PdfKV k="CDN" v="Cloudflare (DDoS-protected)" mono />
          <PdfKV k="TLS FINGERPRINT" v="JA3 · 51c64c77c60f9bbe4cbd9d83…" mono />
          <PdfKV k="MIRROR COUNT" v="14 endpoints across 6 ASNs" mono />
        </div>
      </PDF_Page>

      {/* FINGERPRINT PAGE */}
      <PDF_Page n={3} of={4}>
        <PdfH2 mt={0}>Content Fingerprint &amp; Match</PdfH2>
        <PdfP mt={0}>
          The captured artefact (412pp PDF, 2,148kb) was hashed and compared against the rightsholder's authoritative master file. Both perceptual and exact-content hashes were computed across 412 page-level segments.
        </PdfP>

        <div style={{ marginTop: 16, display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12 }}>
          <div style={{ padding: 12, background: '#fff', border: `1px solid ${J_C.line2}` }}>
            <Mono size={9} color={J_C.fg3} style={{ letterSpacing: '.22em' }}>CAPTURED ARTEFACT</Mono>
            <PdfKV k="SHA-256" v="7E92A4FB…" mono />
            <PdfKV k="pHASH" v="0xA4E1·2F09·8C71" mono />
            <PdfKV k="PAGE COUNT" v="412" mono />
            <PdfKV k="SIZE" v="2,148 kb" mono />
            <PdfKV k="ISBN (META)" v="978-1-9988421-7-3" mono />
          </div>
          <div style={{ padding: 12, background: '#fff', border: `1px solid ${J_C.line2}` }}>
            <Mono size={9} color={J_C.fg3} style={{ letterSpacing: '.22em' }}>MASTER (RIGHTSHOLDER)</Mono>
            <PdfKV k="SHA-256" v="0F88…D219" mono />
            <PdfKV k="pHASH" v="0xA4E1·2F09·8C70" mono />
            <PdfKV k="PAGE COUNT" v="412" mono />
            <PdfKV k="SIZE" v="2,201 kb" mono />
            <PdfKV k="ISBN" v="978-1-9988421-7-3" mono />
          </div>
        </div>

        <div style={{ marginTop: 18, padding: 14, background: 'rgba(107,127,74,.08)', border: `1px solid ${J_C.success}` }}>
          <div style={{ display: 'flex', justifyContent: 'space-between' }}>
            <Mono size={10} color={J_C.fg2} style={{ letterSpacing: '.22em' }}>OVERALL MATCH</Mono>
            <Mono size={10} color={J_C.success} weight={700} style={{ letterSpacing: '.22em' }}>98.7% · HIGH CONFIDENCE</Mono>
          </div>
          <div style={{ marginTop: 8, height: 4, background: 'rgba(64,38,22,.10)', borderRadius: 99, overflow: 'hidden' }}>
            <div style={{ width: '98.7%', height: '100%', background: J_C.success }} />
          </div>
          <PdfP mt={10}>
            412 / 412 pages structurally match. 4 pages exhibit minor compression artefacts (re-encoded), consistent with a reflow through a stripping tool. Cover artwork is byte-identical. Embedded ISBN matches the rightsholder's title-of-record at the registered office.
          </PdfP>
        </div>

        <PdfH2>Chain of Custody</PdfH2>
        <div style={{ padding: 12, background: '#fff', border: `1px solid ${J_C.line2}` }}>
          <PdfKV k="12:14:33Z" v="Scout NEPTUNE indexed candidate" />
          <PdfKV k="12:14:41Z" v="Gemini triage · classified as PIRATED PDF · 0.96 conf" />
          <PdfKV k="12:14:58Z" v="Page snapshot capture (4 angles) · stored to evidence vault" />
          <PdfKV k="12:15:04Z" v="WHOIS + ASN trace + JA3 fingerprint recorded" />
          <PdfKV k="12:15:11Z" v="Content fingerprint computed and matched against master" />
          <PdfKV k="14:11:08Z" v="Operator O. KESTREL authorized via FaceID · KS-0918-44F7" />
          <PdfKV k="14:11:09Z" v="Bundle signed and timestamped (RFC 3161 · sigfox.tsa)" />
        </div>
      </PDF_Page>

      {/* NOTICE PAGE */}
      <PDF_Page n={4} of={4}>
        <PdfH2 mt={0}>Statement of Authority</PdfH2>
        <PdfP mt={0}>
          The undersigned operator certifies, on behalf of <b>Vanguard Press Ltd.</b>, that the captured material identified above infringes the exclusive rights granted to Vanguard Press Ltd. as the registered publisher of the work <i>Atlas of Fog</i>, and that all factual statements in this bundle have been verified through automated forensic capture and reviewed by a credentialed operator.
        </PdfP>

        <PdfH2>Good-Faith Statement</PdfH2>
        <PdfP mt={0}>
          The operator has a good-faith belief that the use of the material described is not authorized by the copyright owner, its agent, or the law. The information in this bundle is accurate to the best of the operator's knowledge, and the operator is authorized to act on behalf of the rightsholder. This statement is made under penalty of perjury where so required by jurisdictional statute (incl. 17 U.S.C. §512(c)(3)).
        </PdfP>

        <PdfH2>Signature Block</PdfH2>
        <div style={{ padding: 16, background: '#fff', border: `1px solid ${J_C.line2}`, position: 'relative' }}>
          <FourCorners color={J_C.success} />
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 18 }}>
            <div>
              <Mono size={9} color={J_C.fg3} style={{ letterSpacing: '.22em' }}>OPERATOR</Mono>
              <div style={{ marginTop: 4, fontFamily: J_FONT, fontSize: 16, fontWeight: 700 }}>Olive Kestrel</div>
              <Mono size={11} color={J_C.fg2} style={{ display: 'block', marginTop: 2 }}>Head of IP Defense · Vanguard Press Ltd.</Mono>
              <Mono size={10} color={J_C.fg3} style={{ display: 'block', marginTop: 8, letterSpacing: '.18em' }}>CLEARANCE · A4</Mono>
            </div>
            <div>
              <Mono size={9} color={J_C.fg3} style={{ letterSpacing: '.22em' }}>SIGNED</Mono>
              <Mono size={13} weight={700} color={J_C.fg1} style={{ display: 'block', marginTop: 2 }}>2026-05-14T14:11:08Z</Mono>
              <Mono size={9} color={J_C.fg3} style={{ display: 'block', marginTop: 4, letterSpacing: '.18em' }}>FaceID · KS-0918-44F7</Mono>
              <Mono size={9} color={J_C.fg3} style={{ display: 'block', marginTop: 4, letterSpacing: '.18em' }}>RFC 3161 TSA · sigfox.tsa.ch</Mono>
            </div>
          </div>
          <div style={{ marginTop: 14, padding: 10, background: J_C.bg0, fontFamily: J_MONO, fontSize: 9.5, color: J_C.fg2, wordBreak: 'break-all', borderRadius: 2 }}>
            -----BEGIN BOOKSENTINEL SIGNATURE-----<br/>
            7E92A4FB28C4 91D88AA13F47 2C61E5C09011 99FE8AB12D0F 1CD3A6F92E58<br/>
            5B27ABCE40D8 8C710F4F61EA 21C2D7F8E9A0 4F2B81D5C619 9008EC2A1F4D<br/>
            -----END BOOKSENTINEL SIGNATURE-----
          </div>
        </div>

        <div style={{ marginTop: 20, padding: 12, border: `1px dashed ${J_C.line2}`, background: 'rgba(193,95,60,.05)' }}>
          <Mono size={9} color={J_C.fg3} style={{ letterSpacing: '.22em' }}>VERIFY THIS BUNDLE</Mono>
          <PdfP mt={4}>
            Independently verify the integrity of this bundle at
            {' '}<Mono color={J_C.primary} size={11} weight={600}>booksentinel.io/verify/7E92A4FB</Mono> {' '}
            or by re-hashing this PDF (SHA-256) and matching against the timestamp authority's record.
          </PdfP>
        </div>
      </PDF_Page>
    </div>
  );
}

// ───── DMCA NOTICE (formal email letter) ─────
function DMCA_Notice() {
  return (
    <div style={{ padding: 24, background: J_C.bg1 }}>
      <div style={{
        width: 720, margin: '0 auto', background: '#FBF8EE',
        boxShadow: '0 18px 40px -20px rgba(64,38,22,.30), 0 1px 0 rgba(64,38,22,.08)',
        padding: '44px 52px 48px', fontFamily: J_FONT, color: J_C.fg1,
        position: 'relative', borderRadius: 2,
      }}>
        <GridBg size={18} alpha={.025} />
        <div style={{ position: 'relative' }}>
          {/* Letterhead */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', borderBottom: `1px solid ${J_C.line2}`, paddingBottom: 14 }}>
            <div>
              <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <svg width="18" height="18" viewBox="0 0 24 24" fill="none">
                  <path d="M12 2 3 5v6c0 5 3.8 9.5 9 11 5.2-1.5 9-6 9-11V5l-9-3Z" stroke={J_C.primary} strokeWidth="1.6"/>
                  <path d="M12 7v10M7 12h10" stroke={J_C.primary} strokeWidth="1.6"/>
                </svg>
                <Mono size={11} weight={700} color={J_C.fg1} style={{ letterSpacing: '.22em' }}>BOOK<span style={{ color: J_C.primary }}>SENTINEL</span></Mono>
              </div>
              <Mono size={9} color={J_C.fg3} style={{ display: 'block', marginTop: 6, letterSpacing: '.18em' }}>
                ON BEHALF OF VANGUARD PRESS LTD.<br/>
                14 BARBICAN ROW · LONDON EC1Y 8AJ · UK
              </Mono>
            </div>
            <div style={{ textAlign: 'right' }}>
              <Mono size={9} color={J_C.fg3} style={{ letterSpacing: '.22em' }}>FORMAL NOTICE</Mono>
              <Mono size={13} weight={700} color={J_C.fg1} style={{ display: 'block', marginTop: 4 }}>NOTICE-2031</Mono>
              <Mono size={9} color={J_C.fg3} style={{ display: 'block', marginTop: 4 }}>2026-05-14 · 14:11:08Z</Mono>
            </div>
          </div>

          {/* email-style headers */}
          <div style={{ marginTop: 18, padding: 14, background: '#fff', border: `1px solid ${J_C.line2}`, borderRadius: 4 }}>
            <EmailHeader k="TO" v="abuse@ovh.com, abuse@r01.ru, legal@cloudflare.com" />
            <EmailHeader k="CC" v="legal@vanguardpress.co.uk, ops@booksentinel.io" />
            <EmailHeader k="FROM" v="takedowns@booksentinel.io (on behalf of Vanguard Press Ltd.)" />
            <EmailHeader k="SUBJECT" v="DMCA / EUCD §17 Takedown · freebooks-vault.ru/atlas-of-fog · Case T-2031" last />
          </div>

          {/* salutation */}
          <PdfP mt={22}>Dear Abuse / Designated Agent,</PdfP>

          <PdfP>
            We are writing on behalf of <b>Vanguard Press Ltd.</b>, the registered publisher and exclusive licensee of the literary work <i>Atlas of Fog</i> by E. Marwick (ISBN 978-1-9988421-7-3). This is a formal notification under 17 U.S.C. §512(c) of the U.S. Digital Millennium Copyright Act and Article 17 of the EU Copyright Directive that protected material owned by our client is being made available without authorization on infrastructure under your administrative control.
          </PdfP>

          <PdfH2 mt={20}>1 · Infringing Material</PdfH2>
          <div style={{ padding: 12, background: '#fff', border: `1px solid ${J_C.line2}`, borderRadius: 3 }}>
            <PdfKV k="WORK" v="Atlas of Fog (E. Marwick, 2024)" />
            <PdfKV k="ISBN" v="978-1-9988421-7-3" mono />
            <PdfKV k="INFRINGING URL" v="hxxps://freebooks-vault[.]ru/atlas-of-fog" mono />
            <PdfKV k="MIRROR ENDPOINTS" v="14 (full list, Appendix B of NOTICE-2031.pdf)" />
            <PdfKV k="HOST IP" v="51.222.84.119 · AS16276 (OVH SAS)" mono />
            <PdfKV k="CONTENT MATCH" v="98.7% against publisher master" />
            <PdfKV k="EVIDENCE BUNDLE" v="booksentinel.io/verify/7E92A4FB" />
          </div>

          <PdfH2>2 · Action Requested</PdfH2>
          <PdfP mt={0}>
            We respectfully request that you, within the windows defined in your published abuse policy and in any case <b>no later than 24 hours</b> from receipt of this notice:
          </PdfP>
          <ol style={{ margin: '8px 0 0 18px', fontFamily: J_FONT, fontSize: 11.5, lineHeight: 1.6, color: J_C.fg1 }}>
            <li>Disable public access to the infringing URL and all mirror endpoints identified in Appendix B.</li>
            <li>Preserve associated server logs, payment records, and registrant data for a minimum of 180 days for potential legal proceedings.</li>
            <li>Acknowledge receipt of this notice in writing and provide a case reference to <Mono color={J_C.primary} size={11}>takedowns@booksentinel.io</Mono>.</li>
            <li>Where the same registrant has been the subject of prior notices, terminate the offending account under your repeat-infringer policy.</li>
          </ol>

          <PdfH2>3 · Statements Required Under Statute</PdfH2>
          <PdfP mt={0}>
            <b>Good-faith belief.</b> I have a good-faith belief that the use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law.
          </PdfP>
          <PdfP>
            <b>Accuracy.</b> The information in this notification is accurate, and under penalty of perjury where so required, I declare that I am authorized to act on behalf of the owner of the exclusive right that is allegedly infringed.
          </PdfP>

          <PdfH2>4 · Authentication</PdfH2>
          <PdfP mt={0}>
            This notice is paired with a signed forensic evidence bundle (<Mono color={J_C.fg1} size={11}>NOTICE-2031.pdf</Mono>, SHA-256 <Mono color={J_C.fg1} size={11}>7E92A4FB…</Mono>, RFC 3161 timestamp <Mono color={J_C.fg1} size={11}>2026-05-14T14:11:09Z</Mono>) and was signed by the rights operator via verified biometric authentication. The bundle's integrity is independently verifiable at the URL above.
          </PdfP>

          {/* Signature */}
          <div style={{ marginTop: 28, paddingTop: 18, borderTop: `1px solid ${J_C.line2}`, display: 'grid', gridTemplateColumns: '2fr 1fr', gap: 18 }}>
            <div>
              <div style={{ fontFamily: '"Snell Roundhand", "Brush Script MT", cursive', fontSize: 30, color: J_C.fg1, fontStyle: 'italic' }}>Olive Kestrel</div>
              <div style={{ height: 1, background: J_C.line2, marginTop: 4 }} />
              <Mono size={11} color={J_C.fg1} weight={600} style={{ display: 'block', marginTop: 6 }}>Olive Kestrel</Mono>
              <Mono size={10} color={J_C.fg2} style={{ display: 'block', marginTop: 1 }}>Head of IP Defense, Vanguard Press Ltd.</Mono>
              <Mono size={10} color={J_C.fg3} style={{ display: 'block', marginTop: 6, letterSpacing: '.18em' }}>OPERATOR ID · KS-0918-44F7</Mono>
            </div>
            <div style={{ textAlign: 'right' }}>
              <Mono size={9} color={J_C.fg3} style={{ letterSpacing: '.22em' }}>SIGNED · BIOMETRIC</Mono>
              <div style={{ marginTop: 8, padding: 10, border: `1px solid ${J_C.success}`, background: 'rgba(107,127,74,.06)', display: 'inline-block' }}>
                <Mono size={9} color={J_C.success} weight={700} style={{ letterSpacing: '.22em' }}>✓ VERIFIED</Mono>
              </div>
              <Mono size={9} color={J_C.fg3} style={{ display: 'block', marginTop: 8, letterSpacing: '.04em' }}>2026-05-14T14:11:08Z</Mono>
            </div>
          </div>

          <Mono size={9} color={J_C.fg3} style={{ display: 'block', marginTop: 22, letterSpacing: '.22em', textAlign: 'center' }}>
            BOOKSENTINEL · TAKEDOWNS@BOOKSENTINEL.IO · NOTICE-2031 · CONFIDENTIAL
          </Mono>
        </div>
      </div>
    </div>
  );
}

const EmailHeader = ({ k, v, last = false }) => (
  <div style={{ display: 'flex', gap: 12, padding: '6px 0', borderBottom: last ? 'none' : `1px solid ${J_C.line}` }}>
    <Mono size={9} color={J_C.fg3} style={{ letterSpacing: '.22em', width: 64, flexShrink: 0 }}>{k}</Mono>
    <Mono size={11} color={J_C.fg1} style={{ wordBreak: 'break-word' }}>{v}</Mono>
  </div>
);

Object.assign(window, { PDF_Bundle, DMCA_Notice });
